Update overall structure of the project
postech-dao/simperby pull request #379
Opened 2023-03-07 15:27 UTC by junha1

2023-03-10 09:26 UTC, JeongHunP approved these changes

2023-03-10 12:35 UTC, TomTaehoonKim requested changes

2023-03-10 12:35 UTC, TomTaehoonKim commented on node/src/lib.rs
> +    /// TODO: remove this and introduce a proper peer discovery protocol
Then will the `Node` structure hold the list of peers?

2023-03-10 18:21 UTC, junha1 commented on test-suite/src/lib.rs
> +            .collect(),
What declaration?

2023-03-11 07:49 UTC, TomTaehoonKim commented on test-suite/src/lib.rs
> +            .collect(),
`ports` field is the second field in the declaration but here, it's in a different position.

2023-03-11 07:56 UTC, TomTaehoonKim commented on test-suite/src/lib.rs
> +            .collect(),
Oops my mistake

2023-03-11 07:56 UTC, TomTaehoonKim approved these changes
LGTM

2023-03-11 11:05 UTC, YoonhoKim0527 approved these changes

2023-03-11 11:31 UTC, merged